use tauri::State;
use crate::state::AppState;
use crate::services::e2e_service::{E2EService, SharedPayload};
use crate::models::item::VaultItem;
use crate::security::SecureKey;
use crate::security::asymmetric::compute_shared_secret;
use crate::security::xchacha20;

#[tauri::command]
pub async fn verify_recipient_email(
    email: String,
    state: State<'_, AppState>,
) -> Result<String, String> {
    let token = state.cloud_session_token.lock().unwrap().clone();
    if token.is_none() {
        return Err("You must be signed in to verify recipients.".to_string());
    }

    let service = E2EService::new(token)?;
    let lookup = service.fetch_public_key(&email).await?;

    Ok(lookup.user_id)
}

#[tauri::command]
pub async fn share_item_e2e(
    item_id: String,
    recipient_email: String,
    state: State<'_, AppState>,
) -> Result<(), String> {
    let token = state.cloud_session_token.lock().unwrap().clone();
    let sender_id = state.cloud_user_id.lock().unwrap().clone();
    
    if token.is_none() || sender_id.is_none() {
        return Err("You must be signed in to share items.".to_string());
    }

    let service = E2EService::new(token)?;

    // 1. Get Recipient Public Key
    let lookup = service.fetch_public_key(&recipient_email).await?;
    let recipient_id = lookup.user_id;
    let recipient_pub_b64 = lookup.public_key;

    // 2. Load Local Vault Item
    let vault_id = state.current_vault_id.lock().unwrap().clone().ok_or("No vault open")?;
    let payload = {
        let key_hierarchy_guard = state.key_hierarchy.lock().unwrap();
        let key_hierarchy = key_hierarchy_guard.as_ref().ok_or("Vault is locked")?;
        
        let uuid = uuid::Uuid::parse_str(&item_id).map_err(|_| "Invalid item ID format")?;
        let item = state.db.get_item(uuid, key_hierarchy)
            .map_err(|_| "Item not found or could not be decrypted")?;
            
        let plaintext_json = serde_json::to_string(&item).map_err(|e| e.to_string())?;

        // 3. Load Sender Private Key
        let (sender_priv_b64, _) = crate::commands::cloud_auth::get_local_x25519_keys(&state.app_dir, sender_id.as_ref().unwrap())?;
        
        let clean_sender_priv = sender_priv_b64.trim_matches('"').trim();
        let clean_recipient_pub = recipient_pub_b64.trim_matches('"').trim();

        // 4. Compute Shared Secret (DH)
        let shared_secret_bytes = compute_shared_secret(clean_sender_priv, clean_recipient_pub)?;
        use zeroize::Zeroizing;
        let shared_key: SecureKey = Zeroizing::new(shared_secret_bytes);
        
        // 6. Encrypt the plaintext specifically for the Recipient using the Shared Secret
        let aad = format!("shared-{}-{}", recipient_id, sender_id.as_ref().unwrap());
        let encrypted_data = xchacha20::encrypt(
            plaintext_json.as_bytes(),
            &shared_key,
            Some(aad.as_bytes())
        ).map_err(|e| e.to_string())?;

        let cipher_b64 = base64::Engine::encode(&base64::engine::general_purpose::STANDARD, &encrypted_data.ciphertext);
        let nonce_b64 = base64::Engine::encode(&base64::engine::general_purpose::STANDARD, &encrypted_data.nonce);

        // 7. Dispatch to Cloud
        SharedPayload {
            id: Some(uuid::Uuid::new_v4().to_string()), // Generated by Sender
            sender_id: sender_id.unwrap(),
            recipient_id,
            vault_id,
            item_id,
            encrypted_payload: cipher_b64,
            nonce: nonce_b64,
            created_at: None,
        }
    };

    service.send_package(payload).await?;

    Ok(())
}

#[derive(serde::Serialize)]
pub struct InboxItem {
    pub package_id: String,
    pub sender_email: String,
    pub vault_id: String,
    pub created_at: String,
}

#[tauri::command]
pub async fn fetch_inbox(state: State<'_, AppState>) -> Result<Vec<InboxItem>, String> {
    let token = state.cloud_session_token.lock().unwrap().clone();
    let recipient_id = state.cloud_user_id.lock().unwrap().clone();
    
    if token.is_none() || recipient_id.is_none() {
        return Ok(Vec::new());
    }

    let service = E2EService::new(token)?;
    let packages = service.check_inbox(recipient_id.as_ref().unwrap()).await?;

    let mut inbox = Vec::new();
    for pkg in packages {
        let sender_email = service.resolve_sender_email(&pkg.sender_id).await.unwrap_or_else(|_| pkg.sender_id.clone());
        
        inbox.push(InboxItem {
            package_id: pkg.id.unwrap_or_default(),
            sender_email,
            vault_id: pkg.vault_id.clone(),
            created_at: pkg.created_at.unwrap_or_default(),
        });
    }

    Ok(inbox)
}

#[tauri::command]
pub async fn accept_shared_item(
    package_id: String,
    state: State<'_, AppState>,
) -> Result<(), String> {
    let token = state.cloud_session_token.lock().unwrap().clone();
    let recipient_id = state.cloud_user_id.lock().unwrap().clone();
    
    if token.is_none() || recipient_id.is_none() {
        return Err("You must be signed in to accept items.".to_string());
    }

    let service = E2EService::new(token.clone())?;
    
    // Check inbox again to find the requested package
    let packages = service.check_inbox(recipient_id.as_ref().unwrap()).await?;
    let pkg = packages.into_iter().find(|p| p.id.as_deref() == Some(package_id.as_str()))
        .ok_or("Package not found or already deleted.")?;

    // Load Recipient Private Key
    let (recipient_priv_b64, _) = crate::commands::cloud_auth::get_local_x25519_keys(&state.app_dir, recipient_id.as_ref().unwrap())?;

    let sender_id = pkg.sender_id;

    // Fetch Sender Public Key directly from `public_keys` table using a reverse lookup
    let sender_pub_b64 = service.fetch_public_key_by_id(&sender_id).await?;

    let clean_recipient_priv = recipient_priv_b64.trim_matches('"').trim();
    let clean_sender_pub = sender_pub_b64.trim_matches('"').trim();

    // Compute Shared Secret (DH)
    let shared_secret_bytes = compute_shared_secret(clean_recipient_priv, clean_sender_pub)?;
    use zeroize::Zeroizing;
    let shared_key: SecureKey = Zeroizing::new(shared_secret_bytes);

    // Decrypt the Shared Payload
    use crate::security::EncryptedData;
    let cipher_bytes = base64::Engine::decode(&base64::engine::general_purpose::STANDARD, &pkg.encrypted_payload).map_err(|e| e.to_string())?;
    let nonce_bytes = base64::Engine::decode(&base64::engine::general_purpose::STANDARD, &pkg.nonce).map_err(|e| e.to_string())?;

    let nonce_len = nonce_bytes.len();
    let cipher_len = cipher_bytes.len();

    let encrypted_data = EncryptedData {
        nonce: nonce_bytes,
        ciphertext: cipher_bytes,
        algorithm: "XChaCha20-Poly1305".to_string(),
    };

    let aad = format!("shared-{}-{}", recipient_id.as_ref().unwrap(), sender_id);
    let plaintext_bytes = xchacha20::decrypt(&encrypted_data, &shared_key, Some(aad.as_bytes())).map_err(|e| {
        format!("Failed to decrypt shared item. AAD: '{}', SenderPub: '{}', NonceLen: {}, CipherLen: {}. SubError: {:?}", 
            aad, sender_pub_b64, nonce_len, cipher_len, e)
    })?;
    
    let plaintext_json = String::from_utf8(plaintext_bytes.to_vec()).map_err(|e| e.to_string())?;

    // Inject into Local Vault
    let (mapped_id, vault_id) = {
        let key_hierarchy_guard = state.key_hierarchy.lock().unwrap();
        let key_hierarchy = key_hierarchy_guard.as_ref().ok_or("Vault is locked")?;
        let vault_id = state.current_vault_id.lock().unwrap().clone().ok_or("No vault open")?;

        let mut decrypted_item: VaultItem = serde_json::from_str(&plaintext_json).map_err(|e| e.to_string())?;
        
        // Brand new local identity
        decrypted_item.id = uuid::Uuid::new_v4(); 
        decrypted_item.title = format!("{} (Shared)", decrypted_item.title);
        decrypted_item.updated_at = chrono::Utc::now().to_rfc3339();

        // Re-Encrypt with Master Key via Database abstraction
        let mapped = state.db.create_item(&decrypted_item, key_hierarchy).map_err(|e| format!("{:?}", e))?;
        (mapped, vault_id)
    };

    // Securely Delete the Package from the Cloud Postal Service
    service.delete_package(pkg.id.as_ref().unwrap()).await?;

    // Push local sync update if Sync is active on this device
    if crate::commands::vault::is_cloud_sync_enabled(&state) {
        if let Ok((data, nonce, _timestamps)) = state.db.get_encrypted_item(mapped_id) {
            if let Ok(sync) = crate::services::sync_service::SyncService::new(token.clone()) {
                 let payload = crate::services::sync_service::SyncPayload {
                    vault_id: vault_id.to_string(),
                    item_id: mapped_id.to_string(),
                    encrypted_payload: data,
                    nonce: nonce,
                    last_modified: chrono::Utc::now().timestamp(),
                    user_id: recipient_id.unwrap(),
                };
                
                tokio::spawn(async move {
                    let _ = sync.push_item(payload).await;
                });
            }
        }
    }

    Ok(())
}

#[tauri::command]
pub async fn delete_shared_item(
    package_id: String,
    state: State<'_, AppState>,
) -> Result<(), String> {
    let token = state.cloud_session_token.lock().unwrap().clone();
    if token.is_none() {
        return Err("You must be signed in to manage your inbox.".to_string());
    }

    let service = E2EService::new(token.clone())?;
    service.delete_package(&package_id).await?;
    Ok(())
}
